// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9uM-5TSMlB715LU0llMcFe2m5cJc3C0o',
    appId: '1:489027201520:web:caa384771782b71f659535',
    messagingSenderId: '489027201520',
    projectId: 'mealplanner-ca213',
    authDomain: 'mealplanner-ca213.firebaseapp.com',
    storageBucket: 'mealplanner-ca213.firebasestorage.app',
    measurementId: 'G-SS5FQ3PFVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkkTSDSX8F4ApCNh2g5p0g7EkgJve7Xi8',
    appId: '1:489027201520:android:196eb88b614d8b55659535',
    messagingSenderId: '489027201520',
    projectId: 'mealplanner-ca213',
    storageBucket: 'mealplanner-ca213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyA1kGWNUJkvJ7xBlxTPSR1gpWomOgQ_c',
    appId: '1:489027201520:ios:44d73246534eaa2c659535',
    messagingSenderId: '489027201520',
    projectId: 'mealplanner-ca213',
    storageBucket: 'mealplanner-ca213.firebasestorage.app',
    iosBundleId: 'com.example.mealplanner',
  );
}
